# Generated by Django 3.1.1 on 2020-09-14 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0003_auto_20200914_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, verbose_name='nombre familia')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='familia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='measurements.family'),
        ),
    ]
