# Generated by Django 3.1.1 on 2020-09-14 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0004_auto_20200914_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='sexo',
            field=models.CharField(blank=True, choices=[('Femenino', 'Femenino'), ('Masculino', 'Masculino')], max_length=10),
        ),
    ]
