# Generated by Django 3.1.1 on 2020-09-14 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0005_person_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='documento',
            field=models.IntegerField(default=0, max_length=15, verbose_name='cédula de ciudadanía'),
        ),
    ]
